# Generated by Django 4.0.4 on 2022-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
