# Generated by Django 4.0.4 on 2022-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ('branch_id', 'branch_name', 'branch_address', 'branch_code'),
            },
        ),
    ]
