# Generated by Django 4.0.4 on 2022-04-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('internal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('internal_modified_datetime', models.DateTimeField(blank=True, null=True)),
                ('product_price', models.FloatField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_branch_id_fk', to='franchise.franchise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_item_fk', to='catalog.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'carts',
                'db_table': 'cart',
            },
        ),
    ]
