# Generated by Django 4.0.4 on 2022-05-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_by',
        ),
    ]
