# Generated by Django 4.0.4 on 2022-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='franchise_order_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
    ]
