# Generated by Django 4.0.4 on 2022-05-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('franchise', '0002_franchise_franchise_order_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_user_id_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
