# Generated by Django 4.0.4 on 2022-05-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'cash'), (2, 'Credit Card'), (3, 'Debit Card')], default=1, null=True),
        ),
    ]
