# Generated by Django 4.0.4 on 2022-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderlogs',
            name='internal_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
