# Generated by Django 4.0.4 on 2022-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_internal_id_orderlogs_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'takeaway'), (2, 'dine'), (3, 'delivery')], default=1, null=True),
        ),
    ]
