# Generated by Django 4.0.4 on 2022-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'AdminCredentials',
                'ordering': ('id', 'name', 'email', 'password'),
            },
        ),
        migrations.CreateModel(
            name='customerData',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=50)),
                ('home_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=50)),
                ('dateofpurchase', models.DateTimeField(auto_now_add=True)),
                ('deliverydate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CustomerData',
                'ordering': ('customer_id', 'fname', 'lname', 'customer_email'),
            },
        ),
    ]
