# Generated by Django 4.0.4 on 2022-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='dateofpurchase',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='deliverydate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
